services:
  # --- Database for Keycloak ---
  keycloak-db:
    image: postgres:15.3
    container_name: keycloak-db
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432" # Host port 5433
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak -d keycloak" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-network

  # --- NEW: Database for Category Service ---
  category-db:
    image: postgres:15.3
    container_name: category-db
    volumes:
      - category_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: category_db
      POSTGRES_USER: category_user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432" # Host port 5434
    networks:
      - microservices-network

  # --- NEW: Database for Product Service ---
  product-db:
    image: postgres:15.3
    container_name: product-db
    volumes:
      - product_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432" # Host port 5435
    networks:
      - microservices-network

  # --- Keycloak Service ---
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db # Connects to the keycloak-db service
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    depends_on:
      keycloak-db:
        condition: service_healthy
    networks:
      - microservices-network

  # --- Zipkin Service ---
  zipkin:
    image: openzipkin/zipkin:2
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - microservices-network

volumes:
  keycloak_db_data:
    driver: local
  # --- NEW: Named volumes for the new databases ---
  category_db_data:
    driver: local
  product_db_data:
    driver: local

networks:
  microservices-network:
    driver: bridge