spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: category-service-api
              uri: lb://category-service
              predicates:
                - Path=/api/v1/categories/**   # distinct prefix
#              filters:
#                - RewritePath=/api/v1/categories/(?<segment>.*), /categories/${segment}

            - id: product-service-api
              uri: lb://product-service
              predicates:
                - Path=/api/v1/products/**     # distinct prefix
#              filters:
#                - RewritePath=/api/v1/products/(?<segment>.*), /api/v1/products/${segment}


            - id: category-service-docs
              uri: lb://category-service
              predicates:
                - Path=/v3/api-docs/category-service
              filters:
                - RewritePath=/v3/api-docs/category-service, /v3/api-docs

            - id: product-service-docs
              uri: lb://product-service
              predicates:
                - Path=/v3/api-docs/product-service
              filters:
                - RewritePath=/v3/api-docs/product-service, /v3/api-docs

  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-microservices-realm

springdoc:
  swagger-ui:
    urls:
      - name: Category Service
        url: /v3/api-docs/category-service
      - name: Product Service
        url: /v3/api-docs/product-service
  api-docs:
    groups:
      enabled: true

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans