spring:
  application:
    name: category-service
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      uri: http://localhost:8888

resilience4j:
  circuitbreaker:
    instances:
      userCB:
        ignore-exceptions:
          - com.example.categoryservice.exception.NotFoundException