spring:
  application:
    name: product-service
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      uri: http://localhost:8888
#  security:
#    oauth2:
#      resource server:
#        jwt:
#          issuer-uri: http://localhost:8181/realms/spring-microservices-realm
#springdoc:
#  api-docs:
#    path: /v3/api-docs