spring:
  application:
    name: keycloak-admin-client
  #  config:
  #    import: "optional:configserver:http://localhost:8888"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-microservices-realm
app:
  keycloak:
    server-url: http://localhost:8181
    realm: spring-microservices-realm
    client-id: api-gateway-client
    client-secret: gLRHd4y6DYdxUTHmJOwbHlDV3xkaK4i5


server:
  port: 9003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true