spring:
  application:
    name: keycloak-admin-client
    # config:
    # import: "optional:configserver:http://localhost:8888" # Temporarily disabled for testing
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://my-keycloak.ddns.net/realms/spring-microservices-realm

  cloud:
    openfeign:
      client:
        config:
          keycloak-auth-client:
            url: ${app.keycloak.server-url}

app:
  keycloak:
    server-url: https://my-keycloak.ddns.net
    realm: spring-microservices-realm
    client-id: api-gateway-client
    client-secret: lhZvA4R3OtOdMqzQZS6NJl8CN7tfavOb

server:
  port: 9003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true